### ISSUE TITLE
OutOfMemory Error

### ISSUE THREAD

**Issue by gzoritchak** [mixitconf/mixit-android#1]
I still have OutOfMemory Error (even after using Picasso for image) during scrolling of speaker list.

```
W/art: "Picasso-7f0700af" prio=5 tid=19 Runnable
         | group="main" sCount=0 dsCount=0 obj=0x32c13a60 self=0xcc654d00
         | sysTid=30282 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0xc5170920
         | state=R schedstat=( 0 0 0 ) utm=256 stm=16 core=7 HZ=100
W/art:   | stack=0xc506e000-0xc5070000 stackSize=1038KB
         | held mutexes= "mutator lock"(shared held)
           at java.lang.Throwable.printStackTrace(Throwable.java:635)
           at java.lang.Throwable.printStackTrace(Throwable.java:626)
           at android.graphics.BitmapFactory.nativeDecodeAsset(Native method)
           at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:700)
           at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:535)
           at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:558)
           at com.squareup.picasso.ResourceRequestHandler.decodeResource(ResourceRequestHandler.java:54)
           at com.squareup.picasso.ResourceRequestHandler.load(ResourceRequestHandler.java:45)
           at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
           at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
           at java.lang.Thread.run(Thread.java:762)
           at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)
       JNI WARNING: java.lang.OutOfMemoryError thrown while calling printStackTrace
I/art: Waiting for a blocking GC Alloc
I/art: Alloc sticky concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 129MB/129MB, paused 600us total 9.701ms
       Starting a blocking GC Alloc
I/art: Waiting for a blocking GC Alloc
I/art: Waiting for a blocking GC Alloc
I/art: Clamp target GC heap from 141MB to 128MB
I/art: Alloc partial concurrent mark sweep GC freed 5(3MB) AllocSpace objects, 0(0B) LOS objects, 1% free, 125MB/128MB, paused 551us total 55.343ms
I/art: WaitForGcToComplete blocked for 324.671ms for cause Alloc
       Starting a blocking GC Alloc
W/System.err: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
I/art: WaitForGcToComplete blocked for 62.678ms for cause Alloc
       Starting a blocking GC Alloc
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.mixitconf, PID: 29419
                  java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
I/art: Clamp target GC heap from 130MB to 128MB
```

**Comment by gzoritchak** [comment]
The main problem comes from speaker images. They are all using JPJ extension but some of them are PNG. As a result they can be really big in memory.

See the difference between:
  1. [mxt_speker_zoritchak.jpg](https://github.com/mixitconf/mixit-android/blob/master/app/src/main/res/drawable/mxt_speker_zoritchak.jpg) 400×400 real JPG: 18.4Ko, 
  2. [mxt_speker_nicoll.jpg](https://github.com/mixitconf/mixit-android/blob/master/app/src/main/res/drawable/mxt_speker_nicoll.jpg) 400×400 PNG using JPG extension: 361 Ko.
